services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_PATH: /data/todo.db
    volumes:
      - todo-db:/etc/todos    # Persist the SQLite DB in a clearer location
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  todo-db:
